accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

projects/urls.py
from django.urls import path
from .views import list_projects, detail_projects, create_projects

urlpatterns = [
    path("", list_projects.as_view(), name="list_projects"),
    path("<int:pk>/", detail_projects.as_view(), name="show_project"),
    path("create/", create_projects.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path
from .views import create_tasks, list_tasks, update_tasks


urlpatterns = [
    path("create/", create_tasks.as_view(), name="create_task"),
    path("mine/", list_tasks.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", update_tasks.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
    path("admin/", admin.site.urls),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(User, related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from projects.models import Project
from django.contrib.auth.models import User

# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField(auto_now_add=False)
    due_date = models.DateTimeField(auto_now_add=False)
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        User, null=True, related_name="tasks", on_delete=models.SET_NULL
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model, authenticate
from tracker.settings import LOGIN_REDIRECT_URL
from django.contrib.auth.models import User

# Create your views here.

user = get_user_model()


def signup(request):
    print(request.method)
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password1"]
            user = User.objects.create_user(
                username, email=None, password=password
            )
            authenticate(request, username=username, password=password)
            user.save()
            return redirect(LOGIN_REDIRECT_URL)
    else:
        form = UserCreationForm()
    return render(
        request,
        template_name="registration/signup.html",
        context={"form": form},
    )

projects/views.py
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView
from projects.models import Project
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.


class list_projects(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class detail_projects(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"


class create_projects(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]

    def get_success_url(self):
        return reverse("show_project", args=[self.object.id])

tasks/views.py
from django.views.generic import CreateView, ListView, UpdateView
from tasks.models import Task
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

# Create your views here.


class create_tasks(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def get_queryset(self):
        return Task.objects.filter(is_completed=self.request.user)

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.id])


class list_tasks(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class update_tasks(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ["is_completed"]

    def get_success_url(self):
        return reverse_lazy("show_my_tasks")

projects/templates/projects/create.html
{% extends 'projects/list.html' %}


{% block content %}
    <main>
        <div>
            <h1>Create a new project</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{%endblock%}

projects/templates/projects/detail.html
{% extends 'projects/list.html' %}
{% load static %}
{% load markdownify %}




{%block content%}
    <main>
        <div>
            <h1>{{project.name}}</h1>
            {{ project.description|markdownify }}
            <h2> Tasks </h2>
            <p> <a href="{% url 'create_task' %}">Create a new task</a></p>
            {% if project.tasks.all%}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Assignee</th>
                            <th>Start date</th>
                            <th>Due date</th>
                            <th>Is completed<th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for task in project.tasks.all %}
                                    <tr>
                                        <td>{{task.name}}</td>
                                        <td>{{task.assignee}}</td>
                                        <td>{{task.start_date}}</td>
                                        <td>{{task.due_date}}</td>
                                        {% if task.is_completed%}
                                            <td>Yes</td>
                                        {% else %}
                                            <td>No</td>

                                        {% endif %}


                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
            {%else%}
                <p>"This project has no tasks."</p>

            {% endif %}



        </div>

    </main>
{%endblock%}

projects/templates/projects/list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>First Page</title>
    </head>

    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url "show_my_tasks"%}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url "list_projects"%}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url "logout"%}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url "login"%}">Login</a>
                        </li>
                        <li>
                            <a href="{% url "signup"%}">Signup</a>
                        </li>
                    {% endif %}
                </nav>
            </header>
            {% block content %}
                <main>
                    <h1>My Projects</h1>
                    <div>
                        <a href="{% url  "create_project" %}">Create a new project</a>
                    </div>


                    {% if project_list %}


                        <table>
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Number of tasks</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for project in project_list %}
                                    <tr>
                                        <td><a href="{% url 'show_project' project.id %}">{{project.name}}</a></td>
                                        <td>{{project.tasks.all|length }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {%else%}
                        <p>"You are not assigned to any projects."</p>

                    {% endif %}


                </div>

                </main>
            {% endblock %}
        </body>

    </html>

tasks/templates/tasks/create.html
{% extends 'projects/list.html' %}


{%block content%}
    <main>
        <div>
            <h1>Create a new task</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{%endblock%}

tasks/templates/tasks/list.html
{% extends 'projects/list.html' %}
{% load static %}

{% block content %}
    <main>
        <div>
            <h1>My Tasks</h1>
            {% if task_list%}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Is completed </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in task_list %}
                            <tr>
                                <td>{{task.name}}</td>
                                <td>{{task.start_date}}</td>
                                <td>{{task.due_date}}</td>
                                {% if is_completed%}
                                    <td> Done </td>
                                {%else%}
                                    <td><form method="post" action="{% url 'complete_task' task.id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="is_completed" value="True">
                                        <button>Complete</button>
                                    </form> </td>
                                {% endif %}
                            </tr>
                        {% endfor%}
                    </tbody>
                </table>
            {%else%}
                <p>You have no tasks</p>

            {% endif %}


        </div>

    </main>
{% endblock %}